In [4]:
import pandas

In [5]:
#importing data
df = pandas.read_csv('/content/student_performance.csv')

# **EDA**

In [6]:
#viewing 1st 5 rows
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [7]:
# viewing last 5 rows
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [8]:
 #statistical summary of the data
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [9]:
# size of the data (r,c)
df.shape

(30, 13)

In [10]:
#name of the available cols
df.columns

Index(['student_id', 'name', 'age', 'gender', 'department', 'semester',
       'math_score', 'science_score', 'english_score', 'programming_score',
       'attendance_percentage', 'city', 'admission_year'],
      dtype='object')

In [11]:
# datatypes of the cols
df.dtypes

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [12]:
#checking if any null values existing , and summing the values
df.isnull().sum()

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [13]:
# viewing the number unique values
df.nunique()

student_id               30
name                     30
age                       3
gender                    2
department                4
semester                  1
math_score               30
science_score            26
english_score            24
programming_score        30
attendance_percentage    27
city                     25
admission_year            1
dtype: int64

In [14]:
# checking for duplicated values of any
df.duplicated().sum()

np.int64(0)

In [15]:
# lisiting the unique values in each cols
for col in df.columns:
    print(col)
    print(df[col].unique())
    print()

student_id
[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028
 1029 1030]

name
['Aarav Sharma' 'Priya Patel' 'Rohit Verma' 'Sneha Reddy' 'Arjun Nair'
 'Meera Joshi' 'Kiran Kumar' 'Divya Singh' 'Rahul Mishra' 'Ananya Das'
 'Vikram Iyer' 'Pooja Gupta' 'Suresh Rao' 'Kavya Nambiar' 'Ajay Tiwari'
 'Ritu Agarwal' 'Manoj Pandey' 'Swati Kulkarni' 'Deepak Chauhan'
 'Nisha Kapoor' 'Harish Pillai' 'Tanvi Mehta' 'Sanjay Dubey'
 'Preeti Saxena' 'Amit Bose' 'Rekha Nair' 'Gaurav Shukla' 'Sunita Pillai'
 'Nitin Jain' 'Akanksha Yadav']

age
[19 20 21]

gender
['Male' 'Female']

department
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

semester
[2]

math_score
[85 76 65 70 92 58 73 88 62 95 80 67 83 74 71 87 56 90 68 79 64 93 61 77
 86 72 84 60 75 91]

science_score
[78 82 74 80 88 66 69 91 71 89 75 72 86 83 61 87 73 84 70 90 81 77 79 65
 76 93]

english_score
[72 88 61 75 81 70 65 84 58 90 68 79 77 82 64 86 55 85 62 67 59 76 73 87]

programming_score
[91 79 55 48 95 52 40 93 45 97 72 44 88 51 76 69 38 92 49 83 58 96 42 53
 89 63 87 39 50 94]

attendance_percentage
[92 87 78 95 90 72 85 96 68 98 83 80 88 91 75 93 65 94 77 89 74 97 70 86
 82 73 84]

city
['Mumbai' 'Ahmedabad' 'Delhi' 'Hyderabad' 'Kochi' 'Pune' 'Bangalore'
 'Lucknow' 'Varanasi' 'Kolkata' 'Chennai' 'Jaipur' 'Mysore' 'Thrissur'
 'Bhopal' 'Agra' 'Patna' 'Nagpur' 'Dehradun' 'Chandigarh'
 'Thiruvananthapuram' 'Surat' 'Allahabad' 'Kanpur' 'Indore']

admission_year
[2023]

In [16]:
# performing operation of performing , count operation on gender , types and number
df["gender"].value_counts()

gender
Male      15
Female    15
Name: count, dtype: int64

In [17]:
# if any missing values exist fill with 0
df.fillna(0)

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68,73,62,49,77,Dehradun,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023
23,1024,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [18]:
# and dropping the cols , with missing values
df.dropna()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68,73,62,49,77,Dehradun,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023
23,1024,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [19]:
df.shape

(30, 13)

In [20]:
df['department']=='Civil'

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15    False
16     True
17    False
18    False
19    False
20    False
21    False
22     True
23    False
24    False
25    False
26    False
27     True
28    False
29    False
Name: department, dtype: bool

In [21]:
df["total_score"] = (df["math_score"] + df["science_score"] + df["english_score"] + df["programming_score"])

df[["name", "total_score"]]

              name  total_score
0     Aarav Sharma          326
1      Priya Patel          325
2      Rohit Verma          255
3      Sneha Reddy          273
4       Arjun Nair          356
5      Meera Joshi          246
6      Kiran Kumar          247
7      Divya Singh          356
8     Rahul Mishra          236
9       Ananya Das          371
10     Vikram Iyer          295
11     Pooja Gupta          262
12      Suresh Rao          334
13   Kavya Nambiar          285
14     Ajay Tiwari          280
15    Ritu Agarwal          325
16    Manoj Pandey          210
17  Swati Kulkarni          354
18  Deepak Chauhan          252
19    Nisha Kapoor          327
20   Harish Pillai          259
21     Tanvi Mehta          367
22    Sanjay Dubey          228
23   Preeti Saxena          287
24       Amit Bose          336
25      Rekha Nair          285
26   Gaurav Shukla          325
27   Sunita Pillai          232
28      Nitin Jain          271
29  Akanksha Yadav          365

In [22]:

topper = df.loc[df["total_score"].idxmax()]
print("Topper:", topper["name"])
print("Score:", topper["total_score"])

Topper: Ananya Das
Score: 371

In [23]:
dept_avg = df.groupby("department")["total_score"].mean().round(2)

In [24]:
dept_avg

department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

In [25]:
sorted_df=df.sort_values(by="total_score", ascending=False)

In [26]:
sorted_df

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year,total_score
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023,371
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023,367
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023,365
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023,356
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023,356
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023,354
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023,336
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023,334
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023,327
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023,326
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023,325
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023,325
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023,325
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023,295
23,1024,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023,287
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023,285
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023,285
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023,280
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023,273
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023,271
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023,262
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023,259
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023,255
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68,73,62,49,77,Dehradun,2023,252
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023,247
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023,246
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023,236
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023,232
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023,228
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023,210

# **MINI PROJECT**

In [27]:
# as per given we have Dataset columns:name ,gender, dept ,math_score ,programming_score, attendance percentage,
# total_score

In [30]:
print("=" * 40)
print("      STUDENT PERFORMANCE EXPLORER")
print("=" * 40)

========================================
      STUDENT PERFORMANCE EXPLORER
========================================

In [31]:
#total number of students
print("Total number of students :", len(df))

Total number of students : 30

In [32]:
#Totalnumber of cols
print("Total number of columns  :", len(df.columns))

Total number of columns  : 14

In [33]:
#Number fo unique depts
print("Unique departments :", df["department"].nunique())

Unique departments : 4

In [36]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year,total_score
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023,326
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023,325
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023,255
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023,273
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023,356

In [34]:
dept_count = df["department"].value_counts()
print(dept_count)

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [38]:
#score analysis
math_highest_score = df["math_score"].max()
math_lowest_score = df["math_score"].min()
math_average_score = df["math_score"].mean()
programming_average_score = df["programming_score"].mean()
attendance_average_score = df["attendance_percentage"].mean()

In [41]:
#printing score analysis
print("Math Highest Score:", math_highest_score)
print("Math Lowest Score:", math_lowest_score)
print("Math Average Score:", math_average_score.round(2))
print("Programming Average Score:", programming_average_score)
print("Attendance Average Score:", attendance_average_score)

Math Highest Score: 95
Math Lowest Score: 56
Math Average Score: 76.07
Programming Average Score: 67.6
Attendance Average Score: 84.5

In [44]:
#gender-wise analysis
gender_avg = df.groupby("gender")["total_score"].mean().round(2)
gender_avg

gender
Female    310.67
Male      280.67
Name: total_score, dtype: float64

In [50]:
#top performers
top_students = df.sort_values(by="total_score",ascending=False).head(5)
toppers=top_students[["name", "department", "total_score"]]
toppers

              name        department  total_score
9       Ananya Das  Computer Science          371
21     Tanvi Mehta  Computer Science          367
29  Akanksha Yadav  Computer Science          365
4       Arjun Nair  Computer Science          356
7      Divya Singh  Computer Science          356

In [54]:
# attendance <75 - condt
low_attendance = df[df["attendance_percentage"] < 75]

if low_attendance.empty:
    print("All students have attendance above 75%")
else:
    for index, row in low_attendance.iterrows():
        print("Name :", row["name"])
        print("Department :", row["department"])
        print("Attendance :", row["attendance_percentage"])
        print(" ")

Name : Meera Joshi
Department : Electronics
Attendance : 72

Name : Rahul Mishra
Department : Mechanical
Attendance : 68

Name : Manoj Pandey
Department : Civil
Attendance : 65

Name : Harish Pillai
Department : Electronics
Attendance : 74

Name : Sanjay Dubey
Department : Civil
Attendance : 70

Name : Sunita Pillai
Department : Civil
Attendance : 73